# Generated by Django 3.0.6 on 2020-06-03 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.TextField(choices=[('A', 'Available'), ('P', 'Pending'), ('T', 'Taken')], default='A', max_length=1)),
                ('pending_until', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
